apiVersion: v1
kind: ConfigMap
metadata:
  name: otus-sw-arch-warehouse-web-server-config
data:
  APP_NAME: {{ .Release.Name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: otus-sw-arch-warehouse-init-job-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
---  
apiVersion: v1
kind: Secret
metadata:
  name: otus-sw-arch-warehouse-web-server-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
---  
apiVersion: v1
kind: Secret
metadata:
  name: otus-sw-arch-warehouse-message-processor-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  MESSAGE_BROKER_URI: {{ printf "amqp://%s:%s@%s:%s/%s" .Values.rabbitmq.username .Values.rabbitmq.password .Values.rabbitmq.host .Values.rabbitmq.port "%2F" | b64enc | quote }}
